version: '3.9'

services:
  db:
    image: postgres:16
    container_name: recipe_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipe_app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: recipe_frontend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/recipe_app
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"

volumes:
  postgres_data: